### ISSUE TITLE
Ajax pagination issue

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#10]
Hi

In AJAX mode there is an issue with link buttons:
take Paging Demo5 example
Then you start you are at page 1. And back button is disable and even red crossed  mouse cursor appear then you put mount over it BUT it still clickable   with this red crossed mouse cursor leading to unpredictable behaviour (can be seen on Paging Demo5 sample). Same thing then you click on last page. Last page button become unavailable but still clickable.

**Comment by joeaudette** [comment]
thanks for the bug report, this is now fixed in version 1.0.1-beta6 as well as in the source code demo

**Comment by dvdobrovolskiy** [comment]
Doh!... I should have check it before. Many tnks!

**Comment by joeaudette** [comment]
I just fixed it this morning thanks to your bug report, you didn't miss anything

**Comment by dvdobrovolskiy** [comment]
many tnks again!
