### ISSUE TITLE
Bag in ajax sample

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#14]
In Ajax sample /Paging/IndexAjax
clicking on current page Icon (should be no action) leads to unpredictable behaviour.

**Comment by dvdobrovolskiy** [comment]
Also Issue  #10 is still not fixed completely. Click on unavailable icon of next page (then you on last page) still clicks. Mean no action happened but page scrolls back to top. (I have some other content before ajaxed list  and then I click next a appear at top of page)

**Comment by joeaudette** [comment]
ok, I fixed it "again" :-D, this time I changed it so a span is used instead of a for current or disabled links
just published nuget 1.0.1-beta8

**Comment by dvdobrovolskiy** [comment]
Many tnanks Joe, and tnks for quick response ))))
