### ISSUE TITLE
the dependency does not support .netframework 4.6

### ISSUE THREAD

**Issue by ahmedanis03** [joeaudette/cloudscribe.Web.Pagination#15]
can you target netstandard1.3 
dun know but i think 4.6  is the sweet spot atm, also i dun know if azure support 4.6.2.
pulled the repo and converted it and the demo works fine after changing to .netstardard1.3.
installed .netframework 4.6.2 and tried to run teh app it  gave reflection expecption and its cause was from this libarary so i pulled the the modified project and refrenced it.
thanks a lot

**Comment by joeaudette** [comment]
if I change it like this, will that be sufficient?:

    "frameworks": {
        "net46": { },
        "netstandard1.5": {
            "imports": "dnxcore50",
            "dependencies": {
                "System.Linq.Queryable": "4.0.1-rc2-24027"
            }
        }
    }
I was confused by the way vs project templates after rc2 only target netstandard, and I'm still not 100% clear about how to correctly target what I should. I do intend for it to work both with .net core and with the full desktop framework

**Comment by joeaudette** [comment]
this solution seems like it is correct, but I'm waiting for your feedback on this and your other issue before I can publish a new nuget

**Comment by ahmedanis03** [comment]
your solution is correct and i was having this headache for 4 hours today to understand how the framework targeting works.
and according to [https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md](url) targeting .netstandard1.3 will gave you both of this worlds. 
as written there.

> In general, class libraries which target a lower .NET Platform Standard version, like 1.0, can be loaded by the largest number of existing platforms, but will have access to a smaller set of APIs. On the other hand, class libraries which target a higher .NET Platform Standard version, like 1.3, can be loaded by a smaller number of newer platforms, but will have access to a larger, more recent set of APIs.

**Comment by joeaudette** [comment]
so by default when you create a new core class library it targets netstandard1.5 but it sounds like if I target netstandard1.0 it will work with the greatest number of platforms including net45 and net46.
It does build when I change it to that and remove net46
I guess the advantage of just using netstandard1.0 as opposed to netstandard1.5 and net46 is not only broader framework support but the resulting nuget has only 1 dll whereas if I target more than one target I get more than one dll in the nuget, ie one dll per target

**Comment by ahmedanis03** [comment]
@joeaudette  yes and Perfect :+1:

**Comment by joeaudette** [comment]
version 1.0.1-beta9 is now available targeting netstandard1.0, please confirm it works for you

**Comment by ahmedanis03** [comment]
confirmed.
working fine thanks

**Comment by joeaudette** [comment]
I wonder is it ok to target netstandard1.0 when I have a dependency on NETStandardLibrary 1.5.0?

      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027",
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final"

    },

    "frameworks": {
        "netstandard1.0": {
            "imports": "dnxcore50",
            "dependencies": {
                "System.Linq.Queryable": "4.0.1-rc2-24027"
            }
        }
    }

or is there a NETStandard.Library 1.0 that I should use?  there does not seem to be one, so I guess it is ok, but seems a little weird. also thought about moving that dependency like this:  

    "dependencies": {  
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final"

    },

    "frameworks": {
        "netstandard1.0": {
            "imports": "dnxcore50",
            "dependencies": {
                "NETStandard.Library": "1.5.0-rc2-24027",
                "System.Linq.Queryable": "4.0.1-rc2-24027"
            }
        }
    }

but I guess with only one target it does not matter where the dependencies go, only with more than one target that would matter

**Comment by ahmedanis03** [comment]
as quoted [Nuget NetStandard Library](https://www.nuget.org/packages/NETStandard.Library/1.5.0-rc2-24027)

> A set of standard .NET API's that are prescribed to be used and supported together. This includes all low level API's that all .NET platforms must support.

so the version here indicate the minimum set of libraries that every .net platform should be support that implies that .netstandard1.0 must support it also
