### ISSUE TITLE
cc-ajax-loading element support

### ISSUE THREAD

**Issue by ahmedanis03** [joeaudette/cloudscribe.Web.Pagination#16]
enable disable loading element as it was in jquery-ajax-unobtrusive

**Comment by joeaudette** [comment]
I have no idea what you are talking about on this issue. could you please explain what you are asking for here.
PagerTagHelper does depend on jquery-ajax-unobtrusive

**Comment by ahmedanis03** [comment]
jquery-ajax-unobtrusive has a feature that support, while loading data from the request it can show/hide a passed element id like this data-ajax-loading="#waitId"
check line 88,100,105 
in [https://github.com/aspnet/jquery-ajax-unobtrusive/blob/0c45b5c2b7ebae286445db1b1e4e578651f52126/jquery.unobtrusive-ajax.js](url) 
it is same like  data-ajax-mode, data-ajax-update, etc 
it would be greate to show a gif while loading

**Comment by joeaudette** [comment]
fyi on both your issues the links you post don't work and result in 404, wrong markdown I think

**Comment by ahmedanis03** [comment]
@joeaudette yea cause copy and paste working file 
sorry kinda new to commenting in github but asp.net core can do more than this ^^

**Comment by joeaudette** [comment]
do you also need data-ajax-loading-duration? or the default will be sufficient?

**Comment by ahmedanis03** [comment]
for me the default would be fine 
Thanks

**Comment by joeaudette** [comment]
ok version 1.0.1-beta9 nuget is now available targeting netstandard1.0 and also adding support for the loader gif as requested. please confirm it works
cs-ajax-loading is the attribute that will map to data-ajax-loading, I also implemented cs-ajax-loading-duration

**Comment by ahmedanis03** [comment]
Tested and working fine
thanks.

**Comment by ahmedanis03** [comment]
dun forget to update the docs for the repo

**Comment by joeaudette** [comment]
the only doc is the readme, I updated it yesterday to include the new settings
