### ISSUE TITLE
Missing ToPagedListAsync

### ISSUE THREAD

**Issue by janekkkk** [joeaudette/cloudscribe.Web.Pagination#17]
It would be nice to have async support when doing database calls with something like ToPagedListAsync() just like there is with toListAsync().

**Comment by joeaudette** [comment]
seems like the same issue as this one from yesterday https://github.com/joeaudette/cloudscribe.Web.Pagination/issues/12
honestly I never intended to build or support any PagedList, I only care about PagerTagHelper which does not depend on PagedList. I think there are other better PagedList implementations and that is a separate concern from rendering pagination links.

so many issues get reported about PagedList I really just want to remove it from my project. I did not set out to build a pagedlist

**Comment by joeaudette** [comment]
but if someone wants to make a pull request implementing async paged list I would accept it, or it is an opportunity to create a separate new project and I could just link to it for anyone who wants a pagedlist impementation to use with PagerTagHelper

**Comment by janekkkk** [comment]
Thanks for the quick reply. I'll try the solution given in the duplicate issue post.
