### ISSUE TITLE
JavaScript errors

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#19]
latest version

/Paging/IndexAjax demo generates JavaScript error. 
"Empty string passed to getElementById()." 
in
/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js
at line 28.
Seems like it still works fine with it but this error prevent my JavaScript placed later to work

**Comment by joeaudette** [comment]
I am unable to produce any error as you describe. I tested with Edge and with Chrome, no errors are shown in the browser dev tools

**Comment by joeaudette** [comment]
only I error I saw when I got a new copy of the repo, was a 404 for /js/site.js
it was a file that I accidentally git ignored. it is an empty js file anyway but I've added it to git to fix the 404
but there no javascript errors at all that I can see

**Comment by dvdobrovolskiy** [comment]
Hm I do not gave it now with latest updated. Sorry seems like issue is closed.
