### ISSUE TITLE
PagerTagHelper baseHref  NullReferenceException

### ISSUE THREAD

**Issue by Luckyvb** [joeaudette/cloudscribe.Web.Pagination#2]
On dnx 4.5.1/core 1.0.0-rc1-final
Problem code:
            **baseHref = linkTemplate.Attributes["href"];**
            querySeparator = baseHref.Contains("?") ? "&" : "?";//NullReferenceException
            baseHref = baseHref + querySeparator + PageNumberParam + "=";

corrected
            baseHref = linkTemplate.Attributes["href"] **?? string.Empty**;
            querySeparator = baseHref.Contains("?") ? "&" : "?";
            baseHref = baseHref + querySeparator + PageNumberParam + "=";

**Comment by joeaudette** [comment]
Thanks! This is now fixed in the code repo and in the nuget https://www.nuget.org/packages/cloudscribe.Web.Pagination/1.0.0-beta5
