### ISSUE TITLE
loading panel

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#20]
Is any way to trigger JavaScript before and after updating grid? I mean to insert panel with animation on top of page while loading data?

**Comment by joeaudette** [comment]
please see these closed issues:
https://github.com/joeaudette/cloudscribe.Web.Pagination/issues/16
https://github.com/joeaudette/cloudscribe.Web.Pagination/issues/18

**Comment by dvdobrovolskiy** [comment]
Damn, Sorry Joe, should have looked.
