### ISSUE TITLE
Attribute Routing and page param

### ISSUE THREAD

**Issue by phinett** [joeaudette/cloudscribe.Web.Pagination#24]
I can't seem to get the page param to work for my routes which use attribute routing, using MVC6 and .Net Core.

For example:

[Route("media/{widgetId}/{page?}]
public IActionResult MediaByWidget(int widgetId, int? page)

It works, but it uses a querystring instead such as:
/media/1/?page=1

**Comment by joeaudette** [comment]
thanks for the bug report. I believe I have fixed this problem, I just published an updated nuget version 1.0.3, can you try it and confirm it solves the problem for you?

**Comment by phinett** [comment]
Thank you that works fine now!
