### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor issue

### ISSUE THREAD

**Issue by dvdobrovolskiy** [joeaudette/cloudscribe.Web.Pagination#26]
Unable to resolve service for type 'Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor' while attempting to activate 'cloudscribe.Web.Pagination.PagerTagHelper'.

**Comment by dvdobrovolskiy** [comment]
Any help with this Joe? It happened after upgrade to .net core 1.0.1

**Comment by dvdobrovolskiy** [comment]
year, Ok

services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
seems like helped.

Developers get rid of IHttpContextAccessor due to performance issues. 
https://github.com/aspnet/Announcements/issues/190

That is the problem of IActionContextAccessor?

**Comment by joeaudette** [comment]
I think you must be using an older version, make your project.json like this to get the latest version:

    "cloudscribe.Web.Pagination": "1.0.*"

and in startup use this:

    services.AddCloudscribePagination();

**Comment by dvdobrovolskiy** [comment]
I use "cloudscribe.Web.Pagination": "1.0.4", 

Yeah services.AddCloudscribePagination(); was missing. strange how it worked before

Many tnks Joe

**Comment by joeaudette** [comment]
glad it is working for you now
