### ISSUE TITLE
Hi, Some issues with CSS ?

### ISSUE THREAD

**Issue by roniaxe** [joeaudette/cloudscribe.Web.Pagination#27]
Hi Joe!

Wanted to thank you for your great project. 
I wanted to ask you, for some reason the pagination CSS seems to look awkward, and I couldn't find the reason since all the static resources looks in place.
I attach a picture of how the pagination looks after forked it from Git.
![image](https://cloud.githubusercontent.com/assets/19142347/19739990/f9761c2e-9b8a-11e6-816e-37c12e718a97.png)

It looks the same pretty much in the other paginations examples.

Hope you can figure out where's the problem.
Thank you !
Roni.

**Comment by joeaudette** [comment]
It is designed to work with [bootstrap css](http://getbootstrap.com/) if you don't use bootstrap then you must style it with your own custom css

**Comment by roniaxe** [comment]
Yeah obviously, but it seems like bootstrap.css is in :
![image](https://cloud.githubusercontent.com/assets/19142347/19740322/4bc7a212-9b8c-11e6-8019-879e9f78e1f6.png)

**Comment by joeaudette** [comment]
you are having this problem with my demo app not in your own project?
Maybe the boostrap is not installed. In Visual Studio 2015, right click the "Dependencies" node in the demo app and then click "Restore Packages". That should make it download and install bootstrap and other client side dependencies. Visual Studio should generally install it automatically but sometimes it may act up and you have to tell it what to do

**Comment by joeaudette** [comment]
the demo app works fine for me

**Comment by roniaxe** [comment]
Yeah it's your demo app . 
I restored the dependencies, but it doesn't seems to make any changes. Bootstrap is installed, as i see the table and other components work with the bootstrap css, but only the pagination is not responding the the bootstrap. Hmm.. this is strange. 
I'll try to deep into it a little more to find why.

**Comment by joeaudette** [comment]
that is very strange indeed, does the problem happen on all the pages with the pager or just one/some?
do you have Visual Studio 2015 update 3?

**Comment by joeaudette** [comment]
I would use the web browser dev tools to look for any errors in the console or any script or css failing to load

**Comment by roniaxe** [comment]
Yeah it happens in all the pages of the demo, but only with the demo.
If i'll start a new project using bootstrap it'll work as expected, with the bootstrap CSS. 
I'm on update 3. Also, my ASPNETCORE_ENVIRONMENT in launchSettings.json is set to Development.

**Comment by joeaudette** [comment]
I just downloaded a new zip copy of this repo, after restoring packages and rebuild solution it works fine, so it is a real mystery why it isn't working for you, especially strange that most of the css works.
are you using Windows or something else?

**Comment by roniaxe** [comment]
It's a mystery indeed :) , I really have hard time understand how come bootstrap is refusing to be loaded. 
I just downloaded a fresh new ZIP of the repo, and hoped i'll see anything different, but it's the same. 
I'm using Windows. 
I'll keep update you as I fix it, hopefully.

**Comment by roniaxe** [comment]
It looks like for some reason bootstrap is not loaded from my static directory, 
Only when copied this line to the body (without conditions) it seems to work fine 
<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css" />
![image](https://cloud.githubusercontent.com/assets/19142347/19743688/4083d144-9b98-11e6-98c3-f2c4ecdb8cd0.png)


This is weird...

**Comment by roniaxe** [comment]
Looking again, it does load, but i think that bootstap.css that comes with the project demo is missing some data. 
For example, can't find navbar-inverse..

**Comment by roniaxe** [comment]
I found the issue , bower is running with --forst-latest flag, which causing it downloading always bootstrap 4, that is missing many of the styles included in 3.* .
this is the bug report :
https://github.com/aspnet/Tooling/issues/665

Thanks for your help !!

**Comment by joeaudette** [comment]
interesting, glad you found the problem
