### ISSUE TITLE
PagedList

### ISSUE THREAD

**Issue by miroslavsiska** [joeaudette/cloudscribe.Web.Pagination#3]
Hi.
If you click on Page one, Pager show items from  page 2.
You can fix it as follows:
       PageIndex = index - 1; // HERE ADD -1 TO FIX THIS PROBLEM

HERE IS PART OF CODE WITH this FIX

    public PagedList(IQueryable<T> source, int index, int pageSize, int? totalCount = null)
        {
            if (index < 0)
                throw new ArgumentOutOfRangeException("index", "Value can not be below 0.");
            if (pageSize < 1)
                throw new ArgumentOutOfRangeException("pageSize", "Value can not be less than 1.");

            if (source == null)
                source = new List<T>().AsQueryable();

            var realTotalCount = source.Count();

            PageSize = pageSize;
            PageIndex = index - 1; // HERE ADD -1 TO FIX THIS PROBLEM
            TotalItemCount = totalCount.HasValue ? totalCount.Value : realTotalCount;
            PageCount = TotalItemCount > 0 ? (int)Math.Ceiling(TotalItemCount / (double)PageSize) : 0;

            HasPreviousPage = (PageIndex > 0);
            HasNextPage = (PageIndex < (PageCount - 1));
            IsFirstPage = (PageIndex <= 0);
            IsLastPage = (PageIndex >= (PageCount - 1));

            ItemStart = PageIndex * PageSize + 1;
            ItemEnd = Math.Min(PageIndex * PageSize + PageSize, TotalItemCount);

            if (TotalItemCount <= 0)
                return;

            var realTotalPages = (int)Math.Ceiling(realTotalCount / (double)PageSize);

            if (realTotalCount < TotalItemCount && realTotalPages <= PageIndex)
                AddRange(source.Skip((realTotalPages - 1) * PageSize).Take(PageSize));
            else
                AddRange(source.Skip(PageIndex * PageSize).Take(PageSize));
        }

**Comment by joeaudette** [comment]
@miroslavsiska said:

> If you click on Page one, Pager show items from page 2.

I'm not seeing any problem like this in the demo web for this project. Please provide detailed steps to produce the problem. I cannot test this fix until I can first reproduce the problem.

**Comment by leozhouchao** [comment]
Hi.
page=1;
return View(_context.Contacts.ToPagedList(page-1,1));
Showing page 1
return View(_context.Contacts.ToPagedList(page,1));
Showing page 2

**Comment by leozhouchao** [comment]
Steps:
1.
project.json file
"Dependencies": added "cloudscribe.Web.Pagination": "1.0.0-beta6"
2.
Startup.cs file
Join using cloudscribe.Web.Pagination;
public void ConfigureServices (IServiceCollection services) in
Join services.AddTransient <IBuildPaginationLinks, PaginationLinkBuilder> ();
3.
_ViewImports.cshtml File
join @addTagHelper "*, cloudscribe.Web.Pagination"
4.
Contraller file
Join using cloudscribe.Web.Pagination;
public IActionResult Index (int page = 1)
         {
             return View (_context.Contacts.ToPagedList (page-1,1));
         }
5.
View file
@model cloudscribe.Web.Pagination.IPagedList<CompanyManagementSystems.Models.Contacts>
.....
navigation:
<Cs-pager cs-paging-pagesize = "@ Model.PageSize"
           cs-paging-pagenumber = "@ Model.PageNumber"
           cs-paging-totalitems = "@ Model.TotalItemCount"
           cs-pagenumber-param = "page"
           asp-controller = "Paging"
           asp-action = "Index"> </ cs-pager>

**Comment by joeaudette** [comment]
this problem does not happen in the demo web app.

I believe it is a bug in your own code.

Specifically, it looks like you are passing pagesize = 1 to pagedlist but you are not setting the page size on the pagertaghelper so it defaults to 10

**Comment by joeaudette** [comment]
if you use pagedlist together with pagertaghelper you must set them both to the same pagesize

**Comment by leozhouchao** [comment]
I changed the code，Debugging。
page=1;
var s = _context.Contacts.ToPagedList(page - 1, 5);
            return View(s);
		Capacity	8	int
		Count	5	int
		HasNextPage	true	bool
		HasPreviousPage	false	bool
		IsFirstPage	true	bool
		IsLastPage	false	bool
		ItemEnd	5	int
		ItemStart	1	int
		PageCount	3	int
		PageIndex	0	int
		PageNumber	1	int
		PageSize	5	int
		TotalItemCount	12	int

page=1;
var s = _context.Contacts.ToPagedList(page, 5);
		Capacity	8	int
		Count	5	int
		HasNextPage	true	bool
		HasPreviousPage	true	bool
		IsFirstPage	false	bool
		IsLastPage	false	bool
		ItemEnd	10	int
		ItemStart	6	int
		PageCount	3	int
		PageIndex	1	int
		PageNumber	2	int
		PageSize	5	int
		TotalItemCount	12	int

By contrast,  I believe that the issue on PageIndex. PageIndex start counting from 0. Maybe I am wrong, I do not know how to set pagertaghelper. sorry, my English is not very good.

**Comment by joeaudette** [comment]
yes pagedlist takes an index parameter and the index is zero based so it is not the same thing as pagenumber

so you need to make a variable
var pageindex = pagenumber -1;
and pass that to pagedlist

pagertaghelper just uses pagenumber, it is not zero based, first page is 1 not 0

you can see this in the demo code
https://github.com/joeaudette/cloudscribe.Web.Pagination/blob/master/src/PagingDemo.Web/Controllers/PagingController.cs

    public IActionResult ProductList(
            int? pageNumber, 
            int? pageSize,
            string query = "")
        {
            int currentPageIndex = pageNumber.HasValue ? pageNumber.Value - 1 : 0;
            int itemsPerPage = pageSize.HasValue ? pageSize.Value : DefaultPageSize;

            var model = new ProductListViewModel();

            model.Products = this.allProducts.Where(p => 
            p.Category.StartsWith(query)
            ).ToPagedList(currentPageIndex, itemsPerPage);

            model.Paging.CurrentPage = pageNumber.HasValue ? pageNumber.Value : 1;
            model.Paging.ItemsPerPage = itemsPerPage;
            model.Paging.TotalItems = model.Products.TotalItemCount;
            model.Query = query; //TODO: sanitize

            return View(model);


        }

**Comment by leozhouchao** [comment]
Thank you, I understand.
