### ISSUE TITLE
Bootstrap 4 compatibility

### ISSUE THREAD

**Issue by cyberyak** [joeaudette/cloudscribe.Web.Pagination#31]
Hi. 

Thank you for your pager component.

Can you please consider implementing additional parameters for cs-pager tag helper, which can allow to implement bootstrap 4 pager. There are lack of attribute parameter for spans and link inside of page "li" item. So we need something like "cs-pager-link-class".

Thanks in advance.

Best regards Dan.

**Comment by joeaudette** [comment]
Hi Dan,

Bootstrap 4 hasn't been released yet afaik it is still in alpha and could change before it is released. Once it is officially released I plan to make all of my projects compatible with it.

I suspect it will not be difficult to make it compatible. What would be helpful is if you could post what the markup needs to look like for pager in bootstrap4, then I would be better able to determine what is needed to support it or whether it could support it currently.

Thanks,

Joe

**Comment by cyberyak** [comment]
Hi Joe,

Understood and agree with you. Right now I've simply applied needed class by jQuery, so it's not a huge problem.

What is needed is just to add class "page-link" to "span" and "a" elements inside of "li".

The link to B4 examples is:
http://v4-alpha.getbootstrap.com/components/pagination/

Thanks in advance for your efforts,
Dan.

**Comment by joeaudette** [comment]
I've just released version 1.1.3 with 2 new attributes cs-pager-link-current-class and cs-pager-link-other-class, so for bootstrap4  you could set those both to page-link.
Link Text is allowed to contain html so it should be possible to also put extra spans or markup in as needed but you may have to implement a custom IBuildPaginationLinks to make that happen.

**Comment by cyberyak** [comment]
Thank you, Joe. Really appreciate that.

**Comment by joeaudette** [comment]
you're welcome! I look forward to bootstrap4 when it gets released. I'm going to go ahead and close this issue
