### ISSUE TITLE
Pagination Not Working

### ISSUE THREAD

**Issue by AndyEV** [joeaudette/cloudscribe.Web.Pagination#33]
So I've installed the library in my application and configured just as directed both in the read me and sample project, I went on bringing in the sample paging controller inside my project with the view to test the library and everything was just responding as expected. Now, I'm pulling data from database, making sure everything is in the same picture like the paging controller and all I can see is my data table no display of any pagination beneath the table and the code is there with every thing well set but still nothing is coming up for pagination. My data is showing with my filter box ontop but pagination isn't responding but it working fine with the sample paging controller I added to the project.

My project is on Dotnet core 1.1

What could be the problem? there's no error per say. 

Just found out that the pagination tag helper isn't rendering, the div closing it is empty.

**Comment by joeaudette** [comment]
sorry for some reason I did not get email notification of this issue and just noticed it.

Did you add this in your _ViewImports.cshtml file as indicated in the [readme](https://github.com/joeaudette/cloudscribe.Web.Pagination/blob/master/README.md)?

    @addTagHelper "*, cloudscribe.Web.Pagination"

**Comment by joeaudette** [comment]
if you continue having trouble please post more details about how you are using it ie your markup.

It will only render if the total item count is higher than the page size, ie if there are more pages of data.

**Comment by AndyEV** [comment]
Okay, yes I did so I finally found a way to make it work.

So if am using `cs-paging-info="@Model.Paging"` it doesn't work but if am braking it down like this
`cs-paging-pagesize="@Model.PageSize"
          cs-paging-pagenumber="@Model.PageNumber"
          cs-paging-totalitems="@Model.TotalItemCount"`
the above works perfectly well...

**Comment by joeaudette** [comment]
sounds like your paging model was not populated correctly in the controller action, I use it all the time,  but fine to use the individual params instead. closing this issue since it is working for you.

**Comment by Pinski** [comment]
@AndyEV 
If `cs-paging-pagesize="@Model.PageSize"` works then `cs-paging-info="@Model"` should work too, right?  It seems the model you are using on that page is the PaginationSettings class directly.

**Comment by tylndemirci** [comment]
Hello, my index selecting bar also not working. If I write manually from address bar of which page should be showed, it works though. Only problem is like I said the bar is not visible. (.Net Core 3)
Even if I manually type the values, it does not help. Thank you in advance.
![image](https://user-images.githubusercontent.com/60180444/83914997-126a6500-a77b-11ea-9246-ceda396108bd.png)
@addTagHelper *, cloudscribe.Web.Pagination is in viewimport.
