### ISSUE TITLE
Pagination control no longer working with Bootstrap 4 beta

### ISSUE THREAD

**Issue by yogiderek** [joeaudette/cloudscribe.Web.Pagination#34]
I recently updated my code to use the latest version of Boostrap and the Pagination component is no longer drawing itself correctly. I get this (text only no borders etc)

Prev123456Next

I assume this is because the Pagination component has been rewritten using flexbox 

https://getbootstrap.com/docs/4.0/migration/#pagination

**Comment by joeaudette** [comment]
I will focus on bootstrap4 after it is released out of beta. However from looking at the docs, in theory you should be able to use it by setting some properties on the pager for the needed css classes like this:

    <cs-pager cs-paging-pagesize="@Model.PageSize"
      cs-paging-pagenumber="@Model.PageNumber"
      cs-paging-totalitems="@Model.TotalItemCount"
      cs-pagenumber-param="page"
      cs-pager-ul-class="pagination"
      cs-pager-li-current-class="page-item active"
      cs-pager-li-other-class="page-item"
      cs-pager-li-non-active-class="page-item disabled"
      cs-pager-link-current-class="page-link"
      cs-pager-link-other-class="page-link"
      asp-controller="YourController"
      asp-action="YourAction"></cs-pager>

**Comment by yogiderek** [comment]
Thanks for this, worked a treat.
