### ISSUE TITLE
Features with no working examples

### ISSUE THREAD

**Issue by Pinski** [joeaudette/cloudscribe.Web.Pagination#36]
Hello,

I've been experimenting with this library for about a week and so far I really love it.  It does a lot with minimal set up and is really powerful.  I'm getting a lot of great functionality with minimal code on my part.  

But, it's been hard setting up the library and using it correctly.  It has required a lot of trial and error on my part.  Furthermore, there's a lot of features in this package and I'm having a hard time finding examples for some of them in the sample project and documentation.  In particular I'm having difficulty with cs-next-page-html and cs-ajax-loading.  For cs-next-page-html, I ended up just having razor encode the html into a string and put it into the -text property.  Works fine but doesn't seem optimal.  I haven't been able to figure out cs-ajax-loading at all.

A sample or two in the sample project for every feature would be very helpful.  I'm using version 1.1.4 if that makes a difference.  I looked at the 2.0 sample project and could not find any additional help there.  

If I missed something, let me know.  Thanks for a great library.

**Comment by joeaudette** [comment]
Hi,
Sorry for the long delay in getting to this issue, I have been very busy with other projects.

I have updated the demo "Paging Demo 2" menu item to use html with glyphicons used in the cs-next-page-html and cs-previous page-page-html

Along the way I found a bug related to that and fixed it and published version 2.1.1 on nuget.org

I've updated the readme with example markup too, note that you should not html encode it. The markup must provide an a element with href='#' so the # can be replaced with an url when needed. And your markup should also include title='Previous page' and Next page as appropriate, ie the cs-next-page-title is not used when you use raw html.

I also updated the ajax demos with a simulated delay when paging and added a loading indicator shown during the delayed loading. I also added success and failure callbacks that just log to the console.
