### ISSUE TITLE
Dealing with a small number of items

### ISSUE THREAD

**Issue by 0xRumple** [joeaudette/cloudscribe.Web.Pagination#37]
Hi,

I was trying out my project asp core 1.1 so I'm using 1.1.4 package... I found this bug:

If you put small number of items like this:

```
private void InitializeProducts()
		{
			for (var i = 0; i < 7; i++) // <=========== JUST 7 items 
			{
				var product = new Product();
				product.Name = "Product " + (i + 1);
				var categoryIndex = i % 4;
				if (categoryIndex > 2)
				{
					categoryIndex = categoryIndex - 3;
				}
				product.Category = allCategories[categoryIndex];
				allProducts.Add(product);
			}
		}
```

It won't show anything on the page and the list will be empty.

My controller action looks like this:
```
public IActionResult Index(int? page)
		{
			var currentPageNum = page.HasValue ? page.Value : 1;

			var model = allProducts.ToPagedList(currentPageNum, 10);

			return View(model);
		}
```

*P.S: different kind of issue appears if you put 15 items.

Hope there is a fix (something like 1.1.5) for people who still use asp core 1.1.

**Comment by 0xRumple** [comment]
I made a decorator fix:

```
public class PagedListViewModel<T> : PagedList<T> where T : class
	{
		public PagedListViewModel(IEnumerable<T> source, int index, int pageSize, int? totalCount = null) : 
			this(source.AsQueryable(), index, pageSize, totalCount)
		{
		}

		public PagedListViewModel(IQueryable<T> source, int index, int pageSize, int? totalCount = null) : 
			base(new List<T>(), index, pageSize, totalCount ?? source.Count())
		{
			var offset = (pageSize * index) - pageSize;
			base.AddRange(source.Skip(offset).Take(pageSize));
		}
	}
```

**Comment by joeaudette** [comment]
If you set the pagesize as 10 and only have 7 items then of course it will not show the pager, that is how it is supposed to work. You are passing in 10 as the page size:

    var model = allProducts.ToPagedList(currentPageNum, 10);

You have not reported any real bug that I can see.

Sorry but I have no plans for any new 1.x releases of any of my projects. I cannot understand why anyone would still be using asp.net core 1.x, I don't think very many people are still using it. I recommend update your own projects to 2.x.

Myself I do not even use PagedList of T class at all. If I were starting this project today I would not even include that. I return [PagedResult of T](https://github.com/joeaudette/cloudscribe.Web.Pagination/blob/master/src/cloudscribe.Pagination.Models/PagedResult.cs) from my page queries.

I regret ever including the PageList of T class in this project and don't care to support it myself. It is a small class so you are free to copy it and "fix" it as you see fit. It is not used in the demo project and I don't ever use it in my own projects. There are also other PagedList of T implementations out there, so you may be able to find a better one. This project is mainly about the PaginationTagHelper which does not rely on PageList of T.

**Comment by 0xRumple** [comment]
Yes the pager won't show but also there won't be any items on the view!

The actual bug is in PagedList of T class... it will be simply empty if you did as above while it should contain the 7 elements, right?

**Comment by joeaudette** [comment]
perhaps, I would have to see more of your code to know if it is a bug, but if it is a bug it is not one that I plan to fix as I plan to remove that class from this project in a future release. As I said you can use your own copy of that class or find a better one.

In general I think one should return a page of data from the db not return all data and then make a PagedList from it. 

I don't want to encourage people to use that class at all. It was originally included from another project and was only included for use in the demo app, but later I removed it from the demo app because I don't want people to use it and having it in the demo encouraged people to use it. At that time I left it in for backward compat in case anyone was using it, but now as bug reports come in for it I just want to remove it completely.

I recommend if you want to use PageList of T, then copy it into your own project and maintain it there because I plan to remove it from this project in a future release.

**Comment by 0xRumple** [comment]
I reproduced it in the attachment.
[Pagination.zip](https://github.com/joeaudette/cloudscribe.Web.Pagination/files/1562684/Pagination.zip)

My actual code is projecting data then make a PagedList:
```
public async Task<IActionResult> Index(string searchTerm = null, int page = 1)
		{
			ViewBag.SearchTerm = searchTerm;

			var agent = await _userManager.GetUserAsync(User);

			var identity = (ClaimsIdentity)User.Identity;
			var claimsPrincipal = new ClaimsPrincipal(identity);

			var students = _agentStudentService.GetAgentStudents(agent, claimsPrincipal)
								.FilterByNameOrEmail(searchTerm)
								.ToStudentDetailsViewModels(_environment);

			var result = students.ToPagedListViewModel(page, 5);

			return View(result);
		}
```

Where students is an IQueryable of StudentDetailsViewModel.

Do you suggest any other better approach?

**Comment by joeaudette** [comment]
The way I would do it is make your method GetAgentStudents return [Paged Result of T](https://github.com/joeaudette/cloudscribe.Web.Pagination/blob/master/src/cloudscribe.Pagination.Models/PagedResult.cs) of your model. ie pass in pagenumber and pagesize as params and only retrieve one page of data at a time from the db.
