### ISSUE TITLE
Changing css of cs-pager

### ISSUE THREAD

**Issue by 13nenad** [joeaudette/cloudscribe.Web.Pagination#39]
Hi Joe,

Is it possible to change the look of the pager element, like background color etc? I tried changing the css base don the class "pagination" but it didn't work for me.

Thanks

**Comment by joeaudette** [comment]
Hi,

CSS does work. The pager just renders html, you can style it with css. By default it uses bootstrap css class names but you can change the classes. If you use bootstrap then your css must come after bootstrap to override it.
