### ISSUE TITLE
Hide disabled prev/next button

### ISSUE THREAD

**Issue by okoetter** [joeaudette/cloudscribe.Web.Pagination#5]
Hi,
is it possible to hide the disabled prev button on first page and the disabled next button on last page?

I could use some CSS to achive this:

```
.pagination > li.disabled {
    display: none;
}
```

But maybe there is or should be a server side solution?

**Comment by joeaudette** [comment]
There was an existing setting that only worked if you were passing in a PaginationSettings object, you could set SuppressEmptyNextPrevious to true.

I've just implemented it so you can also set it on the tag helper if not passing in a PaginationSettings object like this:

    cs-suppress-empty-nextprev="true"

This is available as of version 1.0.1-beta1
